# http://about.travis-ci.org/docs/user/ci-environment/
# http://about.travis-ci.org/docs/user/build-configuration/
# Travis uses Ubuntu 64 12.04

branches:
    only:
        - master
        - travis_pykaldi

language: python
python:
    - "2.7"
compiler:
    - gcc

install:
    # TODO should we not use only from from openblas or just atlas?
    - sudo apt-get update && sudo apt-get install -y build-essential libpng12-dev libfreetype6-dev libopenblas-dev libopenblas-base liblapack-dev gfortran  git python python-dev python-pip libsqlite3-dev wget libatlas-base-dev
    - echo "/usr/lib/atlas-base" | sudo tee /etc/ld.so.conf.d/atlas-lib.conf && sudo ldconfig  # Hack: solution from http://unix.stackexchange.com/questions/52703/using-atlas-from-scipy
    - pip install -r alex-requirements.txt
    # Install pjsip.
    - git clone https://github.com/UFAL-DSG/pjsip.git && pushd pjsip && git checkout travis && ./configure CXXFLAGS=-fPIC CFLAGS=-fPIC LDFLAGS=-fPIC CPPFLAGS=-fPIC && make dep && make && sudo make install && cd pjsip-apps/src/python/ && pip install . && popd && python -c 'import pjsuaxt'
    # Unpack and install precomplied openfst, pykaldi and pyfst
    - wget https://s3-eu-west-1.amazonaws.com/ufal-dsg/pykaldi/pykaldi-travis_2.7.tar.gz/pykaldi/pykaldi_Ubuntu_12.04_LTS.tar.gz && tar xf pykaldi_Ubuntu_12.04_LTS.tar.gz && pushd pykaldi_Ubuntu_12.04_LTS && sudo cp -r openfst/lib/* /usr/local/lib && sudo ldconfig && sudo tar xf pyfst*.tar -C / && sudo tar xf pykaldi*.tar -C / ; popd
    - sudo apt-get install -y libsox-dev
    - easy_install pysox

script:
    - python -c 'import kaldi.decoders'
    - python -c 'import pjsuaxt'
    - python -c 'import alex.applications.vhub'
    - nose2
