# http://about.travis-ci.org/docs/user/ci-environment/
# http://about.travis-ci.org/docs/user/build-configuration/
# Travis uses Ubuntu 64 12.04
branches:
    only:
        - master
        - travis_pykaldi

language: python
python:
    - "2.7" 
compiler:
    - gcc

before_install:
    - sudo apt-get install -y build-essential libpng12-dev libfreetype6-dev python-dev libopenblas-dev libopenblas-base liblapack-dev gfortran  git python python-pip libsqlite3-dev wget
#    - liblapack3 
    # ATLAS matrix library 
    - sudo apt-get install -y build-essential libatlas-base-dev python-dev python-yaml git portaudio19-dev libsox-dev
    - pip install -r alex-requirements.txt
    - easy_install pysox
    - pip install pystache cython flask theano
    - pip install --allow-unverified pyaudio --allow-unverified pyaudio pyaudio
    - pip install pyfst
    - mkdir tmp/
    - cd tmp/
    - git clone https://github.com/UFAL-DSG/pjsip.git
    - cd pjsip
    - ./configure CXXFLAGS=-fPIC CFLAGS=-fPIC LDFLAGS=-fPIC CPPFLAGS=-fPIC
    - make dep
    - make
    - make install
    - cd pjsip-apps/src/python/
    - python setup-pjsuaxt.py install
    # Unpack and install precomplied openfst, pykaldi and pyfst
    - wget https://s3-eu-west-1.amazonaws.com/ufal-dsg/pykaldi/pykaldi-travis_2.7.tar.gz/pykaldi/pykaldi_Ubuntu_12.04_LTS.tar.gz && tar xf pykaldi_Ubuntu_12.04_LTS.tar.gz && pushd pykaldi_Ubuntu_12.04_LTS && sudo cp -r openfst/lib /usr/local/lib && sudo ldconfig && sudo tar pyfst*.tar -C / && sudo tar pykaldi*.tar -C / ; popd

script:
    - echo "preinstalled passed. No tests implemented yet"
